# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b33ec893a8e2244dbccbb7872a2af4dda761f5e482f242270d1565c9d0c1b317f2f2cb26ab4ac756fc44e518a1c7136ca3fb3ff61122570fd36353e1e9c097d4

test:
  secret_key_base: 1d1ecd20c4ebfc72f577b7e823bfe1256f4336dde3f9435bb1e2cea80c29fef7537712949724fb5c4bff7217794a68c8f0c3d41acab35ab09c59eeccda62ed7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
